- name: install core packages
  hosts: "{{ hosts }}"
  become: yes
  tasks:
  - name: install core packages
    ansible.builtin.apt:
      name:
        - prometheus-node-exporter
        - nfs-common
      update_cache: yes
