---
- name: install zsh
  hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: install zsh
      ansible.builtin.apt:
        name: zsh
        state: present
        update_cache: true
      become: true
