---
- hosts: all
  become: yes
  tasks:
    - name: install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates 
          - curl 
          - gnupg-agent
          - software-properties-common
        update_cache: yes
    - name: add apt-key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: add docker repo
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
    - name: install docker 
      ansible.builtin.apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        update_cache: yes
    - name: add userpermissions
      ansible.builtin.shell: "usermod -aG docker vagrant"
